name: 'Pull Request'

# Run this workflow on a pull request to main
on:
  pull_request:
    branches:
      - main

# TODO: Run unit tests when added
jobs:
  pr:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Check that the Dockerfile can build
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: sweatybot

  ##TODO: Create dev PG instance first
  # validate:
  #   name: Validate Deployment
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-southeast-2
      
  #     - name: Initialise Terraform
  #       run: terraform init -backend-config="key=sweatybot.tfstate" -input=false
  #       working-directory: terraform
  #       env:
          

  #     - name: Terraform Plan
  #       run: terraform plan input=false

